// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdqeizrgdasztvbvwanp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkcWVpenJnZGFzenR2YnZ3YW5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODYzNzExOTMsImV4cCI6MjEwMTk0NzE5M30.nygr3L3Dq6Bh3ZjOF5wKnlNvUXPSEwNmMtbMV9pOORA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});